# Generated by Django 5.0.1 on 2024-04-16 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacante', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('disponibles', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('ubicacion', models.TextField()),
                ('requisitos', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
