# Generated by Django 5.0.1 on 2024-04-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
